-- Reconstructed from the queries in your backend (the zip had no SQL file).
-- Run:  mysql -u root -p < schema.sql
CREATE DATABASE IF NOT EXISTS bidmycar; USE bidmycar;
CREATE TABLE users(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL,email VARCHAR(150) NOT NULL UNIQUE,phone VARCHAR(20),password VARCHAR(255) NOT NULL,role VARCHAR(20) DEFAULT 'user',email_verified BOOLEAN DEFAULT FALSE,verification_token VARCHAR(100),verification_expires DATETIME,password_reset_token VARCHAR(100),password_reset_expires DATETIME,wallet_balance DECIMAL(12,2) DEFAULT 0,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE wallet_transactions(id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,type ENUM('credit','debit') NOT NULL,amount DECIMAL(12,2) NOT NULL,description VARCHAR(255),reference_id VARCHAR(100),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX(user_id));
CREATE TABLE vehicles(id VARCHAR(30) PRIMARY KEY,seller_id INT NOT NULL,lot_number VARCHAR(50),title VARCHAR(200),make VARCHAR(80),model VARCHAR(80),year INT,category VARCHAR(50),fuel_type VARCHAR(30),transmission VARCHAR(30),reg_no VARCHAR(30),vin VARCHAR(40),sale_type VARCHAR(20),condition_type VARCHAR(30) DEFAULT 'used',run_and_drive VARCHAR(30),current_bid DECIMAL(12,2) DEFAULT 0,reserve_price DECIMAL(12,2) DEFAULT 0,reserve_met TINYINT DEFAULT 0,buy_it_now_price DECIMAL(12,2),est_retail_value DECIMAL(12,2),bid_count INT DEFAULT 0,auction_ends_in_seconds INT DEFAULT 0,primary_damage VARCHAR(100),secondary_damage VARCHAR(100),sale_status VARCHAR(20) DEFAULT 'available',sold_at DATETIME,sold_to INT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE vehicle_images(id INT AUTO_INCREMENT PRIMARY KEY,vehicle_id VARCHAR(30) NOT NULL,image_url VARCHAR(500) NOT NULL,sort_order INT DEFAULT 0);
CREATE TABLE watchlists(id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,vehicle_id VARCHAR(30) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE(user_id,vehicle_id));
CREATE TABLE auctions(id INT AUTO_INCREMENT PRIMARY KEY,vehicle_id VARCHAR(30) NOT NULL,start_time DATETIME,end_time DATETIME,scheduled_end_time DATETIME,current_end_time DATETIME,extension_seconds INT DEFAULT 120,max_extension_seconds INT DEFAULT 1800,starting_bid DECIMAL(12,2),current_bid DECIMAL(12,2) DEFAULT 0,reserve_price DECIMAL(12,2) DEFAULT 0,reserve_met TINYINT DEFAULT 0,bid_count INT DEFAULT 0,status VARCHAR(20) DEFAULT 'upcoming',high_bidder VARCHAR(100),high_bidder_id INT,settlement_status VARCHAR(30) DEFAULT 'pending',settled_at DATETIME,settlement_reference VARCHAR(100),payment_deadline DATETIME,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE bids(id INT AUTO_INCREMENT PRIMARY KEY,auction_id INT NOT NULL,vehicle_id VARCHAR(30),bidder_id INT NOT NULL,bidder_name VARCHAR(100),bid_amount DECIMAL(12,2),bid_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX(auction_id));
CREATE TABLE vehicle_purchases(id INT AUTO_INCREMENT PRIMARY KEY,vehicle_id VARCHAR(30) NOT NULL UNIQUE,buyer_id INT NOT NULL,purchase_price DECIMAL(12,2),status VARCHAR(20) DEFAULT 'completed',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
